# Generated by Django 4.2.17 on 2025-02-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefreshToken',
            new_name='Token',
        ),
    ]
