# Generated by Django 4.2.17 on 2025-01-07 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_3',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
